version: 1.0.{build}

branches:
  only:
    - master

skip_commits:
  files:
  - LICENCE
  - '**/*.md'

configuration: Release

test: off

build:
      project: Cheers.sln
      verbosity: normal
      publish_nuget: true
      include_nuget_references: true

deploy:
  - provider: NuGet
    api_key:
      secure: YcP8Mo2SR0X6V6/WTnd+aQeIGbHnnEnC4w7t/VDa1NA/wRq5UIxD+Ubvg/da4rJY
    artifact: /.*\.nupkg/
